## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
after_success:
  - julia -e 'cd(Pkg.dir("DiffResults")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("DiffResults")); include(joinpath("docs", "make.jl"))'
